### ISSUE TITLE
Not getting scanned resource after scan finished

### ISSUE THREAD

**Issue by bughunt123** [gokulapap/Reconator#3]

**Comment by gokulapap** [comment]
Yeah working on it to solve the issue !

**Comment by graphyhiren** [comment]
Getting same issue . have scanned 4 hosts , but after scanning it is not displaying into scanned tab. either not saving into database.

**Comment by SagarDhoot** [comment]
same here!

**Comment by gokulapap** [comment]
Soon it will be fixed !

**Comment by gokulapap** [comment]
Will be fixed soon !

**Comment by gokulapap** [comment]
Working on this will be fixed soon !

**Comment by RizwanSiDdiqu1** [comment]
same here!

**Comment by gokulapap** [comment]
The main reason is the script throwing error somewhere before the scan is getting completed, the error rises because of various reasons, that is now fixed by adding a results entry after each tool runs on target ! now you will see the scanned result even some error occurs, but you wont be able to see the result of particular tool which caused the error

**Comment by gokulapap** [comment]
This isssue is fixed ! Raise an issue if it still persists
Note : Delete the current heroku app and re-deploy to see the changes
